spring:
  application:
    name: email-notification-microservice

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    consumer:
      group-id: product-created-event
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.example.core"

server:
  port: 8081